name: Update

on:
  push:
    branches:
      - main
jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/abcdesktopio/openbox.git" .
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Build abcdesktop openbox 18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=18.04
            BASE_IMAGE=ubuntu:18.04
          tags: |
            abcdesktopio/openbox:18.04

      - name: Build abcdesktop openbox 20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=20.04
            BASE_IMAGE=ubuntu:20.04
          tags: |
            abcdesktopio/openbox:20.04

      - name: Build abcdesktop openbox 21.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=21.04
            BASE_IMAGE=ubuntu:21.04
          tags: |
            abcdesktopio/openbox:21.04
            
      - name: Dispatch on repository oc.software
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.ubuntu.18.04
          event-type: dispatch-from-openbox
