name: Update

on:
  push:
    branches:
      - main
jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
            
      - name: Build abcdesktop openbox 18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=18.04
            BASE_IMAGE=ubuntu:18.04
          tags: |
            abcdesktopio/openbox:18.04

      - name: Build abcdesktop openbox 20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=20.04
            BASE_IMAGE=ubuntu:20.04
          tags: |
            abcdesktopio/openbox:20.04

      - name: Build abcdesktop openbox 21.04
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=21.04
            BASE_IMAGE=ubuntu:21.04
          tags: |
            abcdesktopio/openbox:21.04
            
      - name: Dispatch on repository oc.software
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.ubuntu.18.04
          event-type: dispatch-from-openbox
